autoload -Uz vcs_info
setopt prompt_subst

# Enable Git. VCS_info detects git branch and dirty state
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' check-for-changes true

# output format should be .branch-name and * if dirty. Dirty signified by the misc marker %m
zstyle ':vcs_info:git*' formats '.%b%m'
zstyle ':vcs_info:git*' actionformats '.%b%m'

# set %m to "*" if staged/unstaged changes or an active action (e.g. rebase/cherry-pick/bissect, etc.)
+vi-git-dirty-star() {
  if [[ -n ${hook_com[staged]} || -n ${hook_com[unstaged]} || -n ${hook_com[action]} ]]; then
    hook_com[misc]='*'
  else
    hook_com[misc]=''
  fi
}
zstyle ':vcs_info:git*+set-message:*' hooks git-dirty-star

precmd() { vcs_info }

export PS1="%F{yellow}%n@%1~\${vcs_info_msg_0_} =>%f  "

export EDITOR=nvim
alias vim="nvim"
alias v="vim"
alias c="claude"

export PYTHONPATH="/usr/local/lib/python:/usr/local/lib/python/site-packages:/usr/local/lib/python/site-packages/caption_positioning:/usr/local/lib/python/site-packages/dsptools:$PYTHONPATH"

# Bash aliases
alias rm="rm -i"
alias ls="ls -alF"

# Git aliases
alias gh="git hist"
alias gs="git status"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gd="git diff"
alias gds="git diff --staged"
alias gbr="git branch"
alias gco="git checkout"
alias gss="git stash"
alias gsp="git stash pop"
alias gfa="git fetch -a"
alias gpp="git fetch -a && git pull"

# Rails aliases
alias mrmt="rake db:migrate && rake db:rollback && rake db:migrate && rake db:test:prepare"
alias mrm="rake db:migrate && rake db:rollback && rake db:migrate"
alias test!="rake db:test:prepare"
alias rollback!="rake db:rollback"
alias migrate!="rake db:migrate"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

eval "$(rbenv init - zsh)"

. "$HOME/.local/bin/env"

# Added by Antigravity
export PATH="/Users/mozhu/.antigravity/antigravity/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"
